runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: /

- url: /tile.*
  script: tile_handler.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
